### ISSUE TITLE
Adding OPTIC Planner

### ISSUE THREAD

**Issue by jdekarske** [KCL-Planning/ROSPlan#275]
Hello,
I see the OPTIC planner listed in the documentation, but no header file for it in the interfaces nor a binary. Am I missing it? If not, are there plans to include it in the future?

Thanks!

**Comment by m312z** [comment]
We can't include a binary, since OPTIC (if you want to use metrics) needs to be compiled with CPLEX. However, if you have OPTIC compiled then it should work with ROSPlan out of the box, using the same planner interface as POPF - you just need to adjust the planner command in the launch file to execute OPTIC instead.
