### ISSUE TITLE
Action Interface python

### ISSUE THREAD

**Issue by RodrigoCodeBernardo** [KCL-Planning/ROSPlan#292]
Hi, I’ve been using in ROSPLAN the actions interfaces in cpp (http://kcl-planning.github.io/ROSPlan//tutorials/tutorial_10), is there any example of how I can make the actions in python?

**Comment by gerardcanal** [comment]
Hi @RodrigoCodeBernardo, 
We are currently in the process of merging this capability, which is in #285. Until then, the only way to call the action interfaces is from C++. We expect to merge this and provide the capability soon.

Otherwise, another option is to define your own action interface in Python calling the services to update the KB. You may also check https://github.com/dgerod/rosplan_pytools, where there may be some tool to help in that.
