### ISSUE TITLE
extracting "diagnostic_msgs/KeyValue[] parameters"

### ISSUE THREAD

**Issue by erfanshojaei** [KCL-Planning/ROSPlan#301]
Hello,
I am new in ROS and ROSPlan. 
After I run "rosmsg show rosplan_dispatch_msgs/ActionDispatch ", I got:
-----------------------------------------
int32 action_id
int32 plan_id
string name
diagnostic_msgs/KeyValue[] parameters
  string key
  string value
float32 duration
float32 dispatch_time
--------------------------------------------
for example, one of my actions is: 
--------------------------------------------
action_id: 19
plan_id: 0
name: "print"
parameters: 
  - 
    key: "from"
    value: "vtx10"
  - 
    key: "to"
    value: "vtx11"
duration: 40.0
dispatch_time: 140.01800537109375
------------------------------------------
I created a ROS subscriber in c++. In order to extract the "key" & "value" of parameters in the aforementioned action separately, would you please help me to complete the following function in my subscriber? :
---------------------------------------------
void chatterCallback(const rosplan_dispatch_msgs::ActionDispatch::ConstPtr& msg)
{
 ROS_INFO("I heard: [%s]", msg->parameters.?????? );
}
-----------------------------------------

Thank you in advance and regards,
Erfan

**Comment by gerardcanal** [comment]
Hi Erfan,
Similarly to yesterday's issue, this is not an issue with ROSPlan but on how to get information from msgs in c++. 

As shown in the definition, parameters is an array of KeyValue elements. [Here](http://wiki.ros.org/msg) it says that arrays are stored in a `std::vector` in C++. Thus, your `msg->parameters` is a `std::vector<diagnostic_msgs::KeyValue>`. You can iterate over that vector to get every KeyValue, and as you see in the definition, `msg->parameters[i].key` will be the key, and `msg->parameters[i].value` will be the value.

PS. Please format issues accordingly as those are very hard to read otherwise. You can write code blocks by adding \``` before the beginning and appending ``` at the end of the code. Also please try to not open issues in a large bold font.
